"""
Auto-detects the connected ESP32-S3 board's PSRAM bus mode (Quad vs Octal)
and flash size, so the same `pio run -t upload` works unmodified across
every supported ESP32-S3-DevKitC-1 variant (N8R2, N16R8, ...) without the
user having to pick anything.

PSRAM bus mode is a compile-time Kconfig choice baked into the bootloader —
it cannot be detected/switched by the firmware itself at runtime, so this
has to happen here, before the build, by talking to the chip directly over
serial via esptool (the same connect step `pio run -t upload` performs
right before flashing).

If detection fails for any reason (no board plugged in yet, port busy,
older board without the PSRAM-identifying eFuse burned, etc.) this falls
back to the known-good Quad/8MB config instead of guessing.
"""

import os
import subprocess
import sys

Import("env")  # noqa: F821

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
DETECTED_FILE = os.path.join(PROJECT_DIR, "sdkconfig.defaults.detected")
SDKCONFIG_CACHE = os.path.join(PROJECT_DIR, "sdkconfig.esp32s3")

FALLBACK_MODE = "quad"
FALLBACK_FLASH_MB = 8
VALID_FLASH_MB = (1, 2, 4, 8, 16, 32, 64, 128)

# esp32s3.py's get_psram_cap() -> embedded PSRAM size (MB); 2MB is the only
# Quad-mode PSRAM Espressif ships, everything else currently shipping is Octal.
PSRAM_CAP_TO_MODE = {1: "oct", 2: "quad", 3: "oct", 4: "oct"}


def find_upload_port():
    port = env.subst("$UPLOAD_PORT")  # noqa: F821
    if port and port != "$UPLOAD_PORT":
        return port
    try:
        from serial.tools import list_ports
    except ImportError:
        return None
    candidates = list(list_ports.comports())
    if not candidates:
        return None
    # Prefer Espressif's own USB-Serial/JTAG VID, then common USB-UART bridges.
    for vid in (0x303A, 0x10C4, 0x1A86):
        for c in candidates:
            if c.vid == vid:
                return c.device
    if len(candidates) == 1:
        return candidates[0].device
    return None  # ambiguous — don't guess which port is the board


def import_esptool_cmds():
    """
    esptool's own package unconditionally imports `intelhex` at import time
    (for .hex file support we don't use), which isn't part of PlatformIO's
    Python environment by default. Self-heal by installing it into that same
    environment the first time this is needed, rather than requiring every
    user to fix their machine by hand.
    """
    platform = env.PioPlatform()  # noqa: F821
    esptool_dir = platform.get_package_dir("tool-esptoolpy")
    if not esptool_dir or esptool_dir not in sys.path:
        sys.path.insert(0, esptool_dir)

    try:
        from esptool.cmds import detect_chip, detect_flash_size
    except ModuleNotFoundError as exc:
        if exc.name != "intelhex":
            raise
        python = env.subst("$PYTHONEXE") or sys.executable  # noqa: F821
        subprocess.check_call(
            [python, "-m", "pip", "install", "--quiet", "intelhex"]
        )
        from esptool.cmds import detect_chip, detect_flash_size

    return detect_chip, detect_flash_size


def detect_board(port):
    """Returns (mode, flash_mb) or None if detection wasn't possible."""
    detect_chip, detect_flash_size = import_esptool_cmds()

    esp = detect_chip(port=port)
    try:
        flash_size_str = detect_flash_size(esp) or ""
        flash_mb = None
        if flash_size_str.endswith("MB"):
            try:
                candidate = int(flash_size_str[:-2])
                if candidate in VALID_FLASH_MB:
                    flash_mb = candidate
            except ValueError:
                pass

        mode = FALLBACK_MODE
        if hasattr(esp, "get_psram_cap"):
            psram_cap = esp.get_psram_cap()
            mode = PSRAM_CAP_TO_MODE.get(psram_cap, FALLBACK_MODE)
            if psram_cap not in PSRAM_CAP_TO_MODE:
                print(
                    "warbler32: no embedded PSRAM eFuse detected "
                    f"(cap={psram_cap}) — assuming Quad/N8R2-compatible board"
                )

        print(
            f"warbler32: detected board — PSRAM mode={mode}, "
            f"flash={flash_mb or FALLBACK_FLASH_MB}MB"
        )
        return mode, (flash_mb or FALLBACK_FLASH_MB)
    finally:
        esp.hard_reset()
        esp._port.close()


def write_detected_config(mode, flash_mb):
    fragment_path = os.path.join(PROJECT_DIR, f"sdkconfig.defaults.{mode}")
    with open(fragment_path, "r") as f:
        fragment = f.read()

    content = (
        "# Generated by scripts/detect_board.py — do not edit by hand.\n"
        f"{fragment}"
        f"CONFIG_ESPTOOLPY_FLASHSIZE_{flash_mb}MB=y\n"
    )

    previous = ""
    if os.path.isfile(DETECTED_FILE):
        with open(DETECTED_FILE, "r") as f:
            previous = f.read()

    if content != previous:
        with open(DETECTED_FILE, "w") as f:
            f.write(content)
        # Force IDF to regenerate sdkconfig from the new defaults instead of
        # reusing a stale cached config from a previously detected board.
        if os.path.isfile(SDKCONFIG_CACHE):
            os.remove(SDKCONFIG_CACHE)


def main():
    mode, flash_mb = FALLBACK_MODE, FALLBACK_FLASH_MB
    try:
        port = find_upload_port()
        if port:
            detected = detect_board(port)
            if detected:
                mode, flash_mb = detected
        else:
            print(
                "warbler32: no board detected on a serial port yet — "
                f"using fallback config (PSRAM={FALLBACK_MODE}, "
                f"flash={FALLBACK_FLASH_MB}MB)"
            )
    except Exception as exc:  # noqa: BLE001 — never let detection break the build
        print(f"warbler32: board auto-detection failed ({exc}); using fallback config")

    write_detected_config(mode, flash_mb)

    board = env.BoardConfig()  # noqa: F821
    board.update(
        "build.cmake_extra_args",
        "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.detected",
    )
    board.update("upload.flash_size", f"{flash_mb}MB")


main()
